spec_version: 1.2
package: quartz_metadata

database:
  kind: postgres
  host: ${POSTGRES_HOST:-db}
  port: 5432
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASSWORD:-changeme}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: http://hasura:8080
  admin_secret: ${ADMIN_SECRET:-changeme}
  select_limit: ${SELECT_LIMIT:-10000}
  allow_aggregations: false
  rest: true

contracts:
  quartz_minter_mainnet:
    address: KT1TnVQhjxeNvLutGvzwZvYtC7vKRpwPWhc6
    typename: ubisoft_quartz_minter

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
  aleph:
    kind: http
    url: ''

indexes:
  mint_operations:
    kind: operation
    datasource: tzkt_mainnet
    contracts:
      - quartz_minter_mainnet
    handlers:
      - callback: on_mint
        pattern:
          - destination: quartz_minter_mainnet
            entrypoint: mint

hooks:
  resolve_task_manager:
    callback: resolve_task_manager
  resolver_job:
    callback: resolver_job

jobs:
  resolver_job:
    hook: resolver_job
    daemon: True

advanced:
  metadata_interface: True
  scheduler:
    apscheduler.job_defaults.max_instances: 3
  reindex:
    manual: exception
    migration: exception
    rollback: ignore
    config_modified: ignore
    schema_modified: ignore
